In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn import cluster, neighbors, svm, metrics, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df = pd.read_csv("diabetes.csv",sep=",")

print("#QUESTÃO 4.1\n\n")
#QUESTÃO 4.1


#Verifica quantos dados estão duplicados
print("Duplicado:",df.duplicated().sum())


#Verifica quantos dados estão faltando
print("\n\nFaltando: \n%s" %(df.isnull().sum()))

#QUESTÃO 4.1


Duplicado: 0


Faltando: 
Pregnancies                  0
Gender                       0
Glucose                      0
BloodPressure                0
SkinThickness                0
Insulin                      0
BMI                          0
DiabetesPedigreeFunction     0
Age                          0
Outcome                      0
CalorieIntake               15
Exercise                     0
SleepDuration                0
dtype: int64


In [3]:
#Elimina todos os registros onde Insuline tem valor 0
#Essa eliminação foi feita mediante pesquisa e consulta
#Percebeu-se que vários dos registros com insulina 0
#estavam como a pessoa sadia
#e vários dos registros com insulina 0 estavam como
#pessoa doente, o que não faz sentido.
#Para garantir, ainda, foi feita uma consulta a
#um médico e ele me confirmou que não há insulina 0,
#há insulinas bem próximas de 0 e que, nessas circuns-
#tâncias a pessoa apresenta algum quadro de diabetes.
#Portante, para garantir a integridade dos dados,
#foi feita a eliminação de todos onde a insulina é 0.
df = df.loc[df['Insulin']!=0] 

print("Valores '0':")
print("Qnt. Glucose '0':",len(df.loc[df['Glucose']==0]))
print("Qnt. BloodPressure '0':",len(df.loc[df['BloodPressure']==0]))
print("Qnt. SkinThickness '0':",len(df.loc[df['SkinThickness']==0]))
print("Qnt. Insulin '0':",len(df.loc[df['Insulin']==0]))
print("Qnt. BMI '0':",len(df.loc[df['BMI']==0]))
print("Qnt. DiabetesPedigreeFunction '0':",len(df.loc[df['DiabetesPedigreeFunction']==0]))
print("Qnt. Age '0':",len(df.loc[df['Age']==0]))
print("Qnt. CalorieIntake '0':",len(df.loc[df['CalorieIntake']==0]))
print("Qnt. SleepDuration '0':",len(df.loc[df['SleepDuration']==0]))

Valores '0':
Qnt. Glucose '0': 1
Qnt. BloodPressure '0': 0
Qnt. SkinThickness '0': 0
Qnt. Insulin '0': 0
Qnt. BMI '0': 1
Qnt. DiabetesPedigreeFunction '0': 0
Qnt. Age '0': 0
Qnt. CalorieIntake '0': 0
Qnt. SleepDuration '0': 0


In [173]:
print("Minimos e Máximos:\n\n")
#Feito a limpeza, vamos analizar a integridade dos dados
print("GLUCOSE:")
print("Max.:",max(df['Glucose']),"\tMin.:",min(df['Glucose']))
#Observando que os valores estão numa faixa considerada possível,
#exceto pelo valor mínimo da Glicose ser 0 (que iremos tratar pos-
#teriormente), não iremos tratar outliers da Glicose.

print("BLOODPRESSURE:")
print("Max.:",max(df['BloodPressure']),"\tMin.:",min(df['BloodPressure']))
#Observando que os valores estão numa faixa considerada possível,
#não iremos tratar outliers da pressão sanguínea.

print("SKINTHICKNESS:")
print("Max.:",max(df['SkinThickness']),"\tMin.:",min(df['SkinThickness']))
#Observando que os valores estão numa faixa considerada possível,
#não iremos tratar outliers da expessura da pele.

print("INSULIN:")
print("Max.:",max(df['Insulin']),"\tMin.:",min(df['Insulin']))
#Observando que os valores estão numa faixa considerada possível,
#não iremos tratar outliers da Insulina.

print("BMI:")
print("Max.:",max(df['BMI']),"\tMin.:",min(df['BMI']))
#Observando os valores, tanto o mínimo quanto o máximo estão
#fora do normal. Não existe IMC 0 e não existe IMC tão alto
#(baseado em consultas e pesquisas na internet).
#Desta forma iremos considerar o outlier a seguir.


#Substituindo o limite inferior (0) pela mediana
df['BMI'] = df['BMI'].replace(0,df['BMI'].median())

#Calcula a média e o desvio Padrão
mean  = np.mean(df['BMI'], axis=0)
sd    = np.std(df['BMI'], axis=0)

#Calcula o limite
limit = mean + 2*sd

#Exclui os registros onde há outliers positivos
df = df.loc[df['BMI']<=limit] 


print("BMI:")
print("Max.:",max(df['BMI']),"\tMin.:",min(df['BMI']))
#Agora observe que tanto o máximo, quanto o mínimo atendem ao
#esperado

print("DIABETESPEDIGREEFUNCTION:")
print("Max.:",max(df['DiabetesPedigreeFunction']),"\tMin.:",min(df['DiabetesPedigreeFunction']))
#Agora observe que tanto o máximo, quanto o mínimo atendem ao
#esperado

print('AGE')
print("Max.:",max(df['Age']),"\tMin.:",min(df['Age']))
#Agora observe que tanto o máximo, quanto o mínimo atendem ao
#esperado

print('CALORIEINTAKE')
print("Max.:",df['CalorieIntake'].max(),"\tMin.:",df['CalorieIntake'].min())
#Agora observe que tanto o máximo, quanto o mínimo atendem ao
#esperado


print('SLEEPDURATION')
print("Max.:",df['SleepDuration'].max(),"\tMin.:",df['SleepDuration'].min())
#Agora observe que tanto o máximo, quanto o mínimo atendem ao
#esperado

#A partir da consulta feita, percebe-se que existem 1 caso em que a
#glicose 0 e o IMC (BMI) também foi 0. Nessas ocasiões, pode-se
#substituir o valor pela mediana.
df['Glucose'] = df['Glucose'].replace(0, df['Glucose'].median())

Minimos e Máximos:


GLUCOSE:
Max.: 198 	Min.: 0
BLOODPRESSURE:
Max.: 110 	Min.: 24
SKINTHICKNESS:
Max.: 63 	Min.: 7
INSULIN:
Max.: 846 	Min.: 14
BMI:
Max.: 67.1 	Min.: 0.0
BMI:
Max.: 46.8 	Min.: 18.2
DIABETESPEDIGREEFUNCTION:
Max.: 2.329 	Min.: 0.085
AGE
Max.: 81 	Min.: 21
CALORIEINTAKE
Max.: 9980.0 	Min.: 1510.0
SLEEPDURATION
Max.: 15 	Min.: 4


In [4]:
#Substituindo textos por números
#M para 0 e F para 1
df['Gender'] = df['Gender'].replace('M',0)
df['Gender'] = df['Gender'].replace('F',1)

#No para 0; Morning para 1; Evening para 2; Both para 3
df['Exercise'] = df['Exercise'].replace('No',0)
df['Exercise'] = df['Exercise'].replace('Morning',1)
df['Exercise'] = df['Exercise'].replace('Evening',2)
df['Exercise'] = df['Exercise'].replace('Both',3)

#Substituindo nulos por medianas
df['CalorieIntake'] = df['CalorieIntake'].replace(np.nan,df['CalorieIntake'].median())

print("Qnt. Diabeticos: ",len(df.loc[df['Outcome']==1]))
print("Qnt. Nao Diabeticos: ",len(df.loc[df['Outcome']==0]))
#Por ter uma gritante diferença entre diabeticos e não diabeticos,
#considero mais prodente eliminar o excesso de onde há mais
#(melhor do que criar "na sorte" casos de diabeticos que podem
#"baguncar" meu IA)

df = df.loc[df['Outcome']==0].sample(n=125,random_state=2).append(df.loc[df['Outcome']==1])


print("\n\nQuantidade de diabéticos após balanceamento:")
print("Qnt. Diabeticos: ",len(df.loc[df['Outcome']==1]))
print("Qnt. Nao Diabeticos: ",len(df.loc[df['Outcome']==0]))
#Agora está devidamente balanceada

Qnt. Diabeticos:  130
Qnt. Nao Diabeticos:  264


Quantidade de diabéticos após balanceamento:
Qnt. Diabeticos:  130
Qnt. Nao Diabeticos:  125


In [5]:
#Para verificar se há algum atributo que obtenha correlação,
#abrindo espaço para redundância, verificamos o gráfico
#gerado pela função a seguir:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')
#Como pode-se ver, praticamente não há correlação. Desta forma
#Nenhuma coluna precisa ser removida.

In [6]:
print("#QUESTÃO 4.2")
#QUESTÃO 4.2

X = df.drop(columns=['Outcome']) 
y = df['Outcome'].values

#Dividindo x do teste,
#x da base
#y do teste
#y da base
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

#QUESTÃO 4.2


In [7]:
#K = 5
knn = neighbors.KNeighborsClassifier(n_neighbors = 5, metric="euclidean", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("Acurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

Acurácia: 0.86
Sensibilidade: 0.52
Especificidade: 0.64
Matriz de confusão:
 [[34  4]
 [ 7 32]]


In [8]:
#K = 6
knn = neighbors.KNeighborsClassifier(n_neighbors = 6, metric="euclidean", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("Acurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

Acurácia: 0.88
Sensibilidade: 0.54
Especificidade: 0.89
Matriz de confusão:
 [[37  1]
 [ 8 31]]


In [9]:
#K = 7
knn = neighbors.KNeighborsClassifier(n_neighbors = 7, metric="euclidean", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("Acurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

Acurácia: 0.87
Sensibilidade: 0.54
Especificidade: 0.80
Matriz de confusão:
 [[36  2]
 [ 8 31]]


In [10]:
#K = 8
knn = neighbors.KNeighborsClassifier(n_neighbors = 8, metric="euclidean", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("Acurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

Acurácia: 0.87
Sensibilidade: 0.54
Especificidade: 0.80
Matriz de confusão:
 [[36  2]
 [ 8 31]]


In [11]:
#K = 9
knn = neighbors.KNeighborsClassifier(n_neighbors = 9, metric="euclidean", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("Acurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

Acurácia: 0.87
Sensibilidade: 0.54
Especificidade: 0.80
Matriz de confusão:
 [[36  2]
 [ 8 31]]


In [12]:
print("QUESTÃO 4.3\n")
#QUESTÃO 4.2

#K = 5 e metric = Hamming
knn = neighbors.KNeighborsClassifier(n_neighbors = 5, metric="hamming", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("\nAcurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

QUESTÃO 4.3


Acurácia: 0.87
Sensibilidade: 0.52
Especificidade: 0.70
Matriz de confusão:
 [[35  3]
 [ 7 32]]


In [13]:
#K = 5 e metric = Jaccard
knn = neighbors.KNeighborsClassifier(n_neighbors = 5, metric="jaccard", algorithm="auto")
knn.fit(X_train,y_train)
result = knn.predict(X_test)

matriz = metrics.confusion_matrix(y_test, result)
print("Acurácia: %0.2f" % (metrics.accuracy_score(y_test, result)))
print("Sensibilidade: %0.2f" % (matriz[0][0]/(matriz[0][0] + matriz[1][1])))
print("Especificidade: %0.2f" % (matriz[1][0]/(matriz[1][0] + matriz[0][1])))
print("Matriz de confusão:\n", matriz)

Acurácia: 0.94
Sensibilidade: 0.53
Especificidade: 1.00
Matriz de confusão:
 [[38  0]
 [ 5 34]]
